### PR TITLE
Update Installers.md

### PR DESCRIPTION
**Pull request by DewSecGitHub**
Updated Installers page to include new installer for macOS Sierra v10.12.

### CODE REVIEW

**Review by DewSecGitHub — COMMENTED** [review]
done

**Comment by LudovicRousseau** [comment]
The web page still does NOT list macOS 10.12.
I tried to push a commit to the repository but got a "denied to LudovicRousseau" error.

**Comment by ryandesign** [comment]
@DewSecGitHub, do you have access to merge this pull request? I removed my own access after I set up the repository, and apparently @LudovicRousseau doesn't have access either. The owner of the smartcardservices organization should be able to add additional committers if needed. Shawn, I think I had made you the owner...

**Comment by DewSecGitHub** [comment]
I have apparently never had permissions for pull requests or updating the pages from the start.  I was anticipating there was some transitions taking place and have been waiting for that to resolve.  To date, I have been blocked from pull requests and updates — hence the reason installers and others have not been able to be posted properly.

**Comment by DewSecGitHub** [comment]
I should clarify, I haven't had since the one time I did post a modification to Installers.md.  After that I was no longer able to perform the tasks.

**Comment by DewSecGitHub** [comment]
Shows that both LudovicRousseau and I are "Member", but not "Contributor".

**Comment by LudovicRousseau** [comment]
The group smartcardservices has 2 owners https://github.com/orgs/smartcardservices/people: @macosforgebot and @mocomoc.

Maybe one of them (@mocomoc ?) can update the status of @DewSecGitHub and myself from Member to Contributor.

**Comment by mocomoc** [comment]
I've made both @DewSecGitHub and @LudovicRousseau owners of smartcardservice organization.  I'm happy to be removed once you confirm everything is working as expected.

**Comment by LudovicRousseau** [comment]
@mocomoc  I works for me.

I just created a PR https://github.com/smartcardservices/smartcardservices/pull/153 to fix the APSL URL (and close https://github.com/smartcardservices/smartcardservices/issues/149) but this PR needs a review. I guess I can't auto review my own PR. So only @DewSecGitHub could review it now?

**Pull request merged**
